name: End-to-end tests

on:
  push:
    branches:
      - master

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Install Server Dependencies
        run: |
          cd backend
          npm install

      - name: Start Server
        run: |
          cd backend
          npm run server

      - name: Cypress run for Frontend
        uses: cypress-io/github-action@v6
        with:
          working-directory: frontend
          start: npm start
