name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with:
          node-version: 20.9
          cache: "npm"
          cache-dependency-path: fronted/package-lock.json
      - run: npm ci
      - run: npm test
