name: End-to-end tests

on:
  push:
    branches:
      - master

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js and Install Dependencies
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: frontend
